---
name: Publish Next Version to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    env:
      # github.head_ref is only available in pull requests, not workflows
      BRANCH_NAME: ${{ github.head_ref || github.ref }}
    steps:
      - uses: percona-platform/checkout@v3
        with:
          ref: "$BRANCH_NAME"

      - uses: percona-platform/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Configure git
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Clean up after tests
        run: git checkout -- tsconfig.json

      - name: Build the assets
        run: npm run build

      - name: Bump version
        run: npm version prerelease

      - name: Publish next version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag next --access public

      - name: Push the new version
        run: git push origin HEAD:"$BRANCH_NAME" --follow-tags
